-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 09:37:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_raizes_livres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_raizes_livres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_raizes_livres` DEFAULT CHARACTER SET utf8 ;
USE `db_raizes_livres` ;

-- -----------------------------------------------------
-- Table `db_raizes_livres`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_raizes_livres`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do usuario sendo a chave primaria',
  `nome` VARCHAR(255) NOT NULL COMMENT 'nome do usuario',
  `email` VARCHAR(255) NOT NULL COMMENT 'email do usuario utillizado para fazer o login no sistema',
  `senha` VARCHAR(255) NOT NULL COMMENT 'senha do usuario para fazer login no sistema',
  `ativo` TINYINT NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'campo para verificar se o usuario foi excluido ou não do sistema e se ele pode ou não acessar o sistema',
  `foto` VARCHAR(255) NULL COMMENT 'campo de anexar a foto do usuario para ser exibida no sistema',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_raizes_livres`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_raizes_livres`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'codigo da categoria e chave primaria',
  `descricao` VARCHAR(255) NOT NULL COMMENT 'descrição da categoria do produto',
  `ativo` TINYINT NOT NULL COMMENT 'campo para verificar se a categoria foi ou não excluida de nosso sistema',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_raizes_livres`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_raizes_livres`.`produto` (
  `id` INT NOT NULL COMMENT 'codigo do produto',
  `id_categoria` INT NOT NULL COMMENT 'chave relacional com a categoria dos produtos',
  `usuario_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL COMMENT 'nome do produto',
  `preco` DECIMAL NOT NULL COMMENT 'valor do produto',
  `descricao` VARCHAR(255) BINARY NOT NULL COMMENT 'campo para identificar se o produto esta excluido ou não de nossa plataforma',
  `foto` VARCHAR(255) NOT NULL COMMENT 'campo para identificar a quantidade de produtos que temos no estoque para poder fazer a venda do mesmo',
  PRIMARY KEY (`id`),
  INDEX `idCategoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_produto_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_raizes_livres`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_raizes_livres`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
